#+TITLE: Phundrak’s dotfiles
#+AUTHOR: Lucien Cartier-Tilet
#+EMAIL: lucien@phundrak.com
#+CREATOR: Lucien Cartier-Tilet
#+LANGUAGE: en
#+OPTIONS: H:4 broken_links:mark email:t ^:{}
#+KEYWORDS: dotfiles linux emacs configuration phundrak drakpa

#+html: <a href="https://archlinux.org/"><img src="https://img.shields.io/badge/OS-Arch%20Linux-10A0CC?logo=Arch%20Linux&logoColor=white&style=flat-square"/></a>

* Presentation
This repository is where I keep most of my configuration files. With
what is stored here, anyone can recreate a working desktop
configuration similar to my daily one.

My dotfiles are managed by [[https://yadm.io/][yadm]], and although I don’t use its
alternate files features (which is pretty neat btw), it allows me to
painlessly manage my dotfiles right where they are and not in a
separate Git repository somewhere with everything symlinked. Another
advantage of yadm is it will automatically execute (with your
authorization, of course) my homemade bootstrap when my dotfiles are
cloned through yadm.

* A lot of things are missing!
Yep, a lot of things are not in this repository but over at
[[https://config.phundrak.com][config.phundrak.com]]. This is where I store all my litterate config.
You can check out its own repo over at
[[https://labs.phundrak.com/phundrak/config.phundrak.com][labs.phundrak.com/phundrak/config.phundrak.com]].

* Neat, what’s the license?
  All of my  dotfiles (and my dotfiles  only) are available under  the GNU GPLv3
  Licence. Please  consult [[file:LICENCE.md]] for  more information. In  short: you
  are free to  access, edit and redistribute  all of my dotfiles  under the same
  licence and as allowed by the licence, and if you fuck up something, it’s your
  own responsibility.
